# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 561e2b4de570254b6b92f3d242ebb47293dc5b391f0136e17d32cede8cc5a89fff6ac97ca6de4ebeb3d51b613d82bf682e54b037538488c38612364ae1a41525

test:
  secret_key_base: 179baece962c96b277c28e5f68860465a8d8105842253dcbb6846af05df6d13ed776d080226943501e46cf0fc995984584bcb16632087531b32c192196af607e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
